#!/bin/sh
# DeskForge hbbr longrun: RustDesk relay server.
#
# Reads /data/id_ed25519 (generated by the key-secret oneshot) and binds to
# the configured relay port (default 21117).
set -eu
cd /data
exec /usr/bin/hbbr -k _
