#!/bin/sh
# DeskForge hbbs longrun: RustDesk ID / rendezvous server.
#
# Reads /data/id_ed25519 (generated by the key-secret oneshot) and binds to
# the configured rendezvous port (default 21116).
set -eu
cd /data
exec /usr/bin/hbbs -k _
