#!/bin/sh
# DeskForge hbbs longrun: RustDesk ID / rendezvous server.
#
# Reads /data/id_ed25519 (generated by the key-secret oneshot) and binds to
# the configured rendezvous port (default 21116).
#
# Decides the -r relay argument by reading /run/s6/container_environment/RELAY
# directly. s6-overlay v3 stores operator-provided -e vars there (one file per
# var, content = value); reading the file is equivalent to inspecting the
# env var that would be set if s6-svscan propagated the env dir to children
# (which it does not by default; with-contenv is the canonical loader).
set -eu
cd /data
RELAY_VALUE=""
if [ -s /run/s6/container_environment/RELAY ]; then
    RELAY_VALUE="$(cat /run/s6/container_environment/RELAY)"
fi
# -r advertises the relay server(s) to clients that can't hole-punch.
# Only pass -r when RELAY is non-empty; an unset/empty RELAY falls back
# to direct connections only (no placeholder domain advertised).
if [ -n "$RELAY_VALUE" ]; then
    exec /command/s6-envdir /run/s6/container_environment /usr/bin/hbbs -r "$RELAY_VALUE" -k _
else
    exec /command/s6-envdir /run/s6/container_environment /usr/bin/hbbs -k _
fi
