"""
Django settings for rdgen project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY','django-insecure-!(t-!f#6g#sr%yfded9(xha)g+=!6craeez^cp+*&bz_7vdk61')
GHUSER = os.environ.get("GHUSER", '')
GHBEARER = os.environ.get("GHBEARER", '')
GENURL = os.environ.get("GENURL", '')
GHBRANCH = os.environ.get("GHBRANCH",'master')
ZIP_PASSWORD = os.environ.get("ZIP_PASSWORD",'insecure')
PROTOCOL = os.environ.get("PROTOCOL", 'https')
REPONAME = os.environ.get("REPONAME", 'rdgen')
SH_SECRET = os.environ.get('SH_SECRET', 'secret')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG_ENV = os.environ.get("DEBUG", "False")
DEBUG = DEBUG_ENV.lower() in ['true', '1', 't']

# Refuse to boot in production with placeholder secrets. Three of the
# defaults above (SECRET_KEY, ZIP_PASSWORD, SH_SECRET) ship insecure
# values so `manage.py` works out of the box for dev, but in production
# they let an attacker forge sessions, decrypt the secrets zip, or
# bypass workflow auth. Fail loud at startup instead.
if not DEBUG:
    _insecure_settings = []
    if SECRET_KEY.startswith('django-insecure-'):
        _insecure_settings.append('SECRET_KEY')
    if ZIP_PASSWORD == 'insecure':
        _insecure_settings.append('ZIP_PASSWORD')
    if SH_SECRET == 'secret':
        _insecure_settings.append('SH_SECRET')
    if _insecure_settings:
        raise RuntimeError(
            "Refusing to start with default insecure values for: "
            + ", ".join(_insecure_settings)
            + ". Set these env vars before deploying with DEBUG=False."
        )

# ALLOWED_HOSTS from env, comma- or space-separated (BUGS.md RD-B5). A wildcard
# '*' trusts any Host header → host-header injection. Keep '*' only as a dev
# convenience under DEBUG; production must list real hostnames or refuse to boot
# (consistent with the insecure-secret checks above).
_allowed_hosts = os.environ.get('ALLOWED_HOSTS', '').replace(',', ' ').split()
if DEBUG:
    ALLOWED_HOSTS = _allowed_hosts or ['*']
else:
    ALLOWED_HOSTS = _allowed_hosts
    if not ALLOWED_HOSTS:
        raise RuntimeError(
            "ALLOWED_HOSTS must be set (comma/space separated) when DEBUG=False. "
            "Refusing to start with a wildcard host (BUGS.md RD-B5)."
        )
#CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split()

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rdgenerator',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'rdgen.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rdgen.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cap POST body size at 200 MiB — fits the largest real artifacts the
# Actions runners post back (signed APK/AppImage/dmg) with headroom,
# and bounds disk/memory abuse on the unauthenticated path before
# SH_SECRET is configured. Set to a different value via env if larger
# artifacts become necessary.
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.environ.get('DATA_UPLOAD_MAX_MEMORY_SIZE', 200 * 1024 * 1024))
